### ISSUE TITLE
php56error

### ISSUE THREAD

**Issue by liuzhentaolzt** [Tim-AutumnWind/phpdnmp#1]
ERROR: Service 'php56' failed to build: Please provide a source image with `from` prior to commit

**Comment by Tim-AutumnWind** [comment]
可以给我看看报错截图吗？


发自我的iPhone

------------------ Original ------------------

**Comment by liuzhentaolzt** [comment]
centos 7.0 




 
---Original---

**Comment by liuzhentaolzt** [comment]
centos7


 
---Original---
